version: '3.8'

services:
  otel-collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=slack-rag-bot
