name: Python Tests (API)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Create virtual environment and install dependencies
      run: |
        uv venv
        uv pip install -e .

    - name: Run tests
      run: |
        uv run pytest tests -v --tb=short
      env:
        REDIS_URL: redis://localhost:6379
